site_name: Plombery
site_url: https://lucafaggianelli.github.io/plombery
copyright: Copyright &copy; 2023 Luca Faggianelli

repo_url: https://github.com/lucafaggianelli/plombery
edit_uri: edit/main/docs/

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  logo: assets/images/mario-pipe-flower.png
  favicon: assets/images/mario-pipe-flower.png

  palette:
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - toc.follow

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  custom_dir: docs/overrides

extra:
  analytics:
    provider: plausible
    property:

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
        - "."

nav:
  - Welcome: index.md
  - Get Started:
    - Install: get-started.md
    - Your first pipeline: create-a-pipeline.md
  - Docs:
    - Pipelines: pipelines.md
    - Tasks: tasks.md
    - Triggers: triggers.md
    - Configuration: configuration.md
    - Deployment: deployment.md
  - Recipes:
    - SSL Certificate Check: recipes/certificates-expiration.md
