"""support dags

Revision ID: 31fec9d2c5ba
Revises: c2a3cb9f639e
Create Date: 2025-10-31 21:06:24.047306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import plombery.database.type_helpers

# revision identifiers, used by Alembic.
revision: str = "31fec9d2c5ba"
down_revision: Union[str, Sequence[str], None] = "c2a3cb9f639e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_run_outputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mimetype", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("encoding", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "start_time", plombery.database.type_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column(
            "end_time", plombery.database.type_helpers.AwareDateTime(), nullable=True
        ),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("task_output_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_output_id"],
            ["task_run_outputs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_taskrun_pipeline", "task_runs", ["pipeline_run_id", "task_id"], unique=True
    )
    op.create_index("idx_taskrun_status", "task_runs", ["status"], unique=False)
    op.add_column(
        "pipeline_runs",
        sa.Column(
            "end_time", plombery.database.type_helpers.AwareDateTime(), nullable=True
        ),
    )
    op.create_index(
        "idx_pipeline_status", "pipeline_runs", ["pipeline_id", "status"], unique=False
    )
    op.drop_column("pipeline_runs", "tasks_run")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pipeline_runs", sa.Column("tasks_run", sqlite.JSON(), nullable=True))
    op.drop_index("idx_pipeline_status", table_name="pipeline_runs")
    op.drop_column("pipeline_runs", "end_time")
    op.drop_index("idx_taskrun_status", table_name="task_runs")
    op.drop_index("idx_taskrun_pipeline", table_name="task_runs")
    op.drop_table("task_runs")
    op.drop_table("task_run_outputs")
    # ### end Alembic commands ###
